name: excel_cmt_tool
description: Đọc Excel nhóm khóa luận, xuất file .cmt binary
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  excel_plus: ^0.0.3
  file_picker: ^8.1.4
  google_fonts: ^6.2.1
  path: ^1.9.0
  flutter_riverpod: ^2.5.1
  archive: ^4.0.9
  crypto: ^3.0.7
  encrypt: ^5.0.3
  google_generative_ai: ^0.4.7
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
